// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaddyWise.Api.Data;

#nullable disable

namespace PaddyWise.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260927190350_AddAccountStatusToUser")]
    partial class AddAccountStatusToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaddyWise.Api.Entities.CropResource.CropActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CultivationCycleId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("LoggedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType");

                    b.HasIndex("CultivationCycleId");

                    b.HasIndex("LoggedByUserId");

                    b.ToTable("CropActivities");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.FieldCultivation.AgentRunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CultivationPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RawOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CultivationPlanId");

                    b.ToTable("AgentRunLogs");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.FieldCultivation.CultivationCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ActualHarvestDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ExpectedHarvestDate")
                        .HasColumnType("date");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SowingDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VarietyId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("VarietyId");

                    b.HasIndex("FieldId", "Season", "Year")
                        .IsUnique();

                    b.ToTable("CultivationCycles");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.FieldCultivation.CultivationPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CultivationCycleId")
                        .HasColumnType("integer");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficerComment")
                        .HasColumnType("text");

                    b.Property<int?>("OfficerId")
                        .HasColumnType("integer");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationErrorsJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CultivationCycleId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("CultivationPlans");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.FieldCultivation.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Divisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            District = "Polonnaruwa",
                            Name = "Medirigiriya",
                            Province = "North Central"
                        },
                        new
                        {
                            Id = 2,
                            District = "Anuradhapura",
                            Name = "Nuwaragam Palatha",
                            Province = "North Central"
                        },
                        new
                        {
                            Id = 3,
                            District = "Anuradhapura",
                            Name = "Tambuttegama",
                            Province = "North Central"
                        },
                        new
                        {
                            Id = 4,
                            District = "Ampara",
                            Name = "Ampara Central",
                            Province = "Eastern"
                        },
                        new
                        {
                            Id = 5,
                            District = "Kurunegala",
                            Name = "Kurunegala West",
                            Province = "North Western"
                        });
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.FieldCultivation.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DivisionId")
                        .HasColumnType("integer");

                    b.Property<int>("FarmerId")
                        .HasColumnType("integer");

                    b.Property<string>("IrrigationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoilType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Fields", t =>
                        {
                            t.HasCheckConstraint("CK_Fields_Area_Positive", "\"Area\" > 0");
                        });
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.FieldCultivation.GrowthStageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CultivationCycleId")
                        .HasColumnType("integer");

                    b.Property<int>("LoggedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ObservedOn")
                        .HasColumnType("date");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CultivationCycleId");

                    b.HasIndex("LoggedByUserId");

                    b.ToTable("GrowthStageLogs");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.FieldCultivation.Variety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Varieties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeGroup = "3 month",
                            DurationDays = 90,
                            Name = "Bg 300"
                        },
                        new
                        {
                            Id = 2,
                            AgeGroup = "3.5 month",
                            DurationDays = 105,
                            Name = "Bg 352"
                        },
                        new
                        {
                            Id = 3,
                            AgeGroup = "3.5 month",
                            DurationDays = 105,
                            Name = "Bg 360"
                        },
                        new
                        {
                            Id = 4,
                            AgeGroup = "3.5 month",
                            DurationDays = 105,
                            Name = "At 362"
                        },
                        new
                        {
                            Id = 5,
                            AgeGroup = "3.5 month",
                            DurationDays = 105,
                            Name = "Bg 94-1"
                        },
                        new
                        {
                            Id = 6,
                            AgeGroup = "3.5 month",
                            DurationDays = 105,
                            Name = "Bg 359"
                        },
                        new
                        {
                            Id = 7,
                            AgeGroup = "3 month",
                            DurationDays = 90,
                            Name = "At 307"
                        },
                        new
                        {
                            Id = 8,
                            AgeGroup = "3.5 month",
                            DurationDays = 105,
                            Name = "Bw 367"
                        });
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.PestDisease.CropObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CropStage")
                        .HasColumnType("integer");

                    b.Property<int>("CultivationCycleId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ObservationType")
                        .HasColumnType("integer");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CultivationCycleId");

                    b.HasIndex("ReportedByUserId");

                    b.ToTable("CropObservations");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.PestDisease.DiagnosisRunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CropObservationId")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RawOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CropObservationId");

                    b.ToTable("DiagnosisRunLogs");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.PestDisease.PestDiseaseKnowledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CropStages")
                        .HasColumnType("text");

                    b.Property<string>("FavorableConditions")
                        .HasColumnType("text");

                    b.Property<string>("ManagementGuidance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PestDiseaseKnowledgeEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8846),
                            CropStages = "Nursery, Tillering",
                            FavorableConditions = "Dry weather, drought-stressed nurseries.",
                            ManagementGuidance = "Maintain adequate field water level; apply an approved insecticide only once infestation passes the economic threshold.",
                            Name = "Thrips",
                            Source = "Sri Lanka Department of Agriculture",
                            Symptoms = "Silvery streaks and curling on young leaves; stunted growth in seedlings.",
                            UpdatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8849)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8851),
                            CropStages = "Tillering, PanicleInitiation",
                            FavorableConditions = "Dense planting, excess nitrogen, continuous flooding, high humidity.",
                            ManagementGuidance = "Avoid excess nitrogen; alternate wetting and drying; favor resistant varieties; targeted insecticide only at economic threshold.",
                            Name = "Brown Planthopper",
                            Source = "Sri Lanka Department of Agriculture",
                            Symptoms = "Yellowing and drying of leaves from the base upward (\"hopperburn\"); stunted, wilting tillers.",
                            UpdatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8851)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8852),
                            CropStages = "Tillering, Flowering",
                            FavorableConditions = "Continuous rice cropping without fallow, high nitrogen.",
                            ManagementGuidance = "Remove and destroy egg masses and post-harvest stubble; use light traps; targeted insecticide once dead-heart incidence passes threshold.",
                            Name = "Yellow Stem Borer",
                            Source = "Sri Lanka Department of Agriculture",
                            Symptoms = "Dead heart (dried central shoot) during vegetative growth; whitehead (empty, upright panicle) at the reproductive stage.",
                            UpdatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8852)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8854),
                            CropStages = "Tillering, PanicleInitiation",
                            FavorableConditions = "High nitrogen, dense canopy, high humidity.",
                            ManagementGuidance = "Balanced nitrogen application; conserve natural enemies; insecticide only above the recommended damage threshold.",
                            Name = "Rice Leaf Folder",
                            Source = "Sri Lanka Department of Agriculture",
                            Symptoms = "Leaves folded longitudinally and webbed together; white/transparent streaks where larvae scrape and feed inside the fold.",
                            UpdatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8854)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8855),
                            CropStages = "PanicleInitiation, Flowering",
                            FavorableConditions = "Warm, humid conditions and dense planting.",
                            ManagementGuidance = "Avoid excess nitrogen and overly dense planting; miticide only under severe, confirmed infestation.",
                            Name = "Rice Sheath Mite",
                            Source = "Sri Lanka Department of Agriculture",
                            Symptoms = "Brown to black lesions on the leaf sheath near the waterline; can cause unfilled or discolored grains.",
                            UpdatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8855)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8857),
                            CropStages = "Nursery, Tillering",
                            FavorableConditions = "High humidity, shaded or low-lying fields, continuous rice cropping.",
                            ManagementGuidance = "Synchronize planting across the area; use resistant varieties; remove wild grasses acting as alternate hosts.",
                            Name = "Rice Gall Midge",
                            Source = "Sri Lanka Department of Agriculture",
                            Symptoms = "Affected tiller produces a tubular \"silvershoot\"/onion-leaf gall instead of a normal leaf whorl and no panicle.",
                            UpdatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8857)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8858),
                            CropStages = "PanicleInitiation, Flowering",
                            FavorableConditions = "High humidity, excess nitrogen, dense planting.",
                            ManagementGuidance = "Avoid excess nitrogen; ensure adequate spacing/drainage for airflow; treat seed and apply fungicide at booting stage if severe.",
                            Name = "Sheath Rot",
                            Source = "Sri Lanka Department of Agriculture",
                            Symptoms = "Reddish-brown lesions on the flag leaf sheath enclosing the panicle; panicle may fail to emerge fully or grains are discolored.",
                            UpdatedAt = new DateTime(2026, 9, 27, 19, 3, 48, 738, DateTimeKind.Utc).AddTicks(8858)
                        });
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.PestDisease.PestDiseaseReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Confidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CropObservationId")
                        .HasColumnType("integer");

                    b.Property<string>("OfficerComment")
                        .HasColumnType("text");

                    b.Property<int?>("OfficerId")
                        .HasColumnType("integer");

                    b.Property<string>("PossibleIssue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CropObservationId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("Status");

                    b.ToTable("PestDiseaseReports");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.Shared.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.CropResource.CropActivity", b =>
                {
                    b.HasOne("PaddyWise.Api.Entities.FieldCultivation.CultivationCycle", "CultivationCycle")
                        .WithMany()
                        .HasForeignKey("CultivationCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaddyWise.Api.Entities.Shared.User", "LoggedByUser")
                        .WithMany()
                        .HasForeignKey("LoggedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CultivationCycle");

                    b.Navigation("LoggedByUser");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.FieldCultivation.AgentRunLog", b =>
                {
                    b.HasOne("PaddyWise.Api.Entities.FieldCultivation.CultivationPlan", "CultivationPlan")
                        .WithMany()
                        .HasForeignKey("CultivationPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CultivationPlan");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.FieldCultivation.CultivationCycle", b =>
                {
                    b.HasOne("PaddyWise.Api.Entities.FieldCultivation.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PaddyWise.Api.Entities.FieldCultivation.Variety", "Variety")
                        .WithMany()
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.FieldCultivation.CultivationPlan", b =>
                {
                    b.HasOne("PaddyWise.Api.Entities.FieldCultivation.CultivationCycle", "CultivationCycle")
                        .WithMany()
                        .HasForeignKey("CultivationCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaddyWise.Api.Entities.Shared.User", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PaddyWise.Api.Entities.Shared.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CultivationCycle");

                    b.Navigation("Officer");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.FieldCultivation.Field", b =>
                {
                    b.HasOne("PaddyWise.Api.Entities.FieldCultivation.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PaddyWise.Api.Entities.Shared.User", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.FieldCultivation.GrowthStageLog", b =>
                {
                    b.HasOne("PaddyWise.Api.Entities.FieldCultivation.CultivationCycle", "CultivationCycle")
                        .WithMany()
                        .HasForeignKey("CultivationCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaddyWise.Api.Entities.Shared.User", "LoggedByUser")
                        .WithMany()
                        .HasForeignKey("LoggedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CultivationCycle");

                    b.Navigation("LoggedByUser");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.PestDisease.CropObservation", b =>
                {
                    b.HasOne("PaddyWise.Api.Entities.FieldCultivation.CultivationCycle", "CultivationCycle")
                        .WithMany()
                        .HasForeignKey("CultivationCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaddyWise.Api.Entities.Shared.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CultivationCycle");

                    b.Navigation("ReportedByUser");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.PestDisease.DiagnosisRunLog", b =>
                {
                    b.HasOne("PaddyWise.Api.Entities.PestDisease.CropObservation", "CropObservation")
                        .WithMany()
                        .HasForeignKey("CropObservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CropObservation");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.PestDisease.PestDiseaseReport", b =>
                {
                    b.HasOne("PaddyWise.Api.Entities.PestDisease.CropObservation", "CropObservation")
                        .WithMany("Reports")
                        .HasForeignKey("CropObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaddyWise.Api.Entities.Shared.User", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CropObservation");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("PaddyWise.Api.Entities.PestDisease.CropObservation", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
